import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  scrollContainer: {
    backgroundColor: '#29B2DD',
    flex: 1,
  },
  scrollContentContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    width: '80%',
    minHeight: 50,
    flex: 0.1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  section: {
    width: '80%',
    flex: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewToday: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 10,
    width: '100%',
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  detailToday: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 10,
    width: '100%',
    height: 130,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  topDetailToday: {
    width: '100%',
    height: '30%',
    paddingLeft: 20,
    paddingRight: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomDetailToday: {
    width: '100%',
    height: '70%',
    paddingLeft: 20,
    paddingRight: 20,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  detailTomorrow: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 10,
    width: '100%',
    height: 160,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  topDetailTomorrow: {
    width: '100%',
    height: '30%',
    paddingLeft: 20,
    paddingRight: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bottomDetailTomorrow: {
    width: '100%',
    height: '70%',
    paddingLeft: 20,
    paddingRight: 20,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
